[options]
work_mode = "sys"
library = "Adw"
version = "1"
girs_directories = ["../../gir-files", "../../"]
min_cfg_version = "1"
external_libraries = [
   "GLib",
   "GObject",
   "Gdk",
   "Gio",
   "Gtk",
   "Pango",
]

ignore = [
   "Adw.VERSION_S", 
   "Adw.MAJOR_VERSION", 
   "Adw.MICRO_VERSION", 
   "Adw.MINOR_VERSION"
]

[[object]]
name = "Adw.SwitchRow"
status = "generate"
version = "1.4" # Drop once https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/839 is merged