image: 'docker.io/bilelmoussaoui/gtk4'

before_script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly
  - source $HOME/.cargo/env
  - meson _build --prefix=/usr -Dlibadwaita:tests=false -Dlibadwaita:examples=false -Dlibadwaita:vapi=false
  - ninja -C _build install
  - git submodule update --init

build:
  script:
    - cargo build --all-features
    - xvfb-run -a -s "-screen 0 1024x768x24" cargo test

pages:
  script:
    # generate the docs
    - cp ./Handy-4.gir ./gir-files
    - cargo build --release --manifest-path ./gir/Cargo.toml
    - ./gir/target/release/gir -c ./libadwaita/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc
    - cargo install rustdoc-stripper
    - /root/.cargo/bin/rustdoc-stripper -g -o ./libadwaita/docs.md
    - cargo doc -p libadwaita -p libadwaita-sys --no-deps --all-features
    - mv target/doc/ public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
