[package]
name = "libadwaita"
version = "0.1.0-alpha"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"
readme = "../README.md"
homepage = "https://world.pages.gitlab.gnome.org/Rust/libadwaita-rs/"
description = "Rust bindings for libadwaita"
license = "MIT"
repository = "https://gitlab.gnome.org/World/Rust/libadwaita-rs"
documentation = "https://world.pages.gitlab.gnome.org/Rust/libadwaita-rs/stable/latest/docs/libadwaita"
categories = ["api-bindings", "gui"]
keywords = ["gtk4-rs", "gnome", "adwaita", "GUI"]

[lib]
name = "libadwaita"

[features]
dox = []

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
libc = '0.2'

[dependencies.glib]
version = "0.14"

[dependencies.gio]
version = "0.14"

[dependencies.gdk-pixbuf]
version = "0.14"

[dependencies.pango]
version = "0.14"

[dependencies.gdk]
package = "gdk4"
version = "0.1"

[dependencies.gtk]
package = "gtk4"
version = "0.1"

[dependencies.ffi]
package = "libadwaita-sys"
path = './sys'
