[package]
name = "libadwaita"
version = "0.1.0"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"

[dependencies]
libc = '0.2'
bitflags = '1.2'
lazy_static = '1.4'
[lib]
name = "libadwaita"

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gdk-pixbuf]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.pango]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gdk]
package = "gdk4"
git = "https://github.com/gtk-rs/gtk4-rs"

[dependencies.gtk]
package = "gtk4"
git = "https://github.com/gtk-rs/gtk4-rs"

[dependencies.ffi]
package = "libadwaita-sys"
path = './sys'

