[external_libraries]
Gio = {min_version = "2.66"}
[options]
girs_directories = ["../gir-files", "../"]
library = "Adw"
version = "1"
min_cfg_version = "1"
target_path = "."
use_gi_docgen = true
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
# with this option enabled, versions for gir and gir-files saved only to one file to minimize noise
single_version_file = true
generate_builder = true

external_libraries = [
   "GLib",
   "GObject",
   "Gdk",
   "GdkPixbuf",
   "Gtk",
   "Pango",
]

generate = [
    "Adw.ActionRow",
    "Adw.Animation",
    "Adw.AnimationState",
    "Adw.Avatar",
    "Adw.Bin",
    "Adw.ButtonContent",
    "Adw.Carousel",
    "Adw.CarouselIndicatorDots",
    "Adw.CarouselIndicatorLines",
    "Adw.CenteringPolicy",
    "Adw.Clamp",
    "Adw.ClampLayout",
    "Adw.ClampScrollable",
    "Adw.ColorScheme",
    "Adw.Easing",
    "Adw.ExpanderRow",
    "Adw.FoldThresholdPolicy",
    "Adw.Flap",
    "Adw.FlapFoldPolicy",
    "Adw.FlapTransitionType",
    "Adw.EnumListItem",
    "Adw.HeaderBar",
    "Adw.Leaflet",
    "Adw.LeafletTransitionType",
    "Adw.NavigationDirection",
    "Adw.PreferencesGroup",
    "Adw.PreferencesPage",
    "Adw.PreferencesRow",
    "Adw.PreferencesWindow",
    "Adw.SplitButton",
    "Adw.SpringAnimation",
    "Adw.SpringParams",
    "Adw.Squeezer",
    "Adw.SqueezerTransitionType",
    "Adw.StatusPage",
    "Adw.SwipeTracker",
    "Adw.Swipeable",
    "Adw.TabView",
    "Adw.TimedAnimation",
    "Adw.ToastPriority",
    "Adw.ViewStack",
    "Adw.ViewSwitcher",
    "Adw.ViewSwitcherBar",
    "Adw.ViewSwitcherPolicy",
    "Adw.ViewSwitcherTitle",
    "Adw.WindowTitle",
]

manual = [
    "GLib.Variant",
    "GObject.Object",
    "GObject.Value",
    "Gdk.Cursor",
    "Gdk.Display",
    "Gdk.DragAction",
    "Gdk.Paintable",
    "Gdk.Rectangle",
    "Gdk.Texture",
    "Gio.Application",
    "Gio.ApplicationFlags",
    "Gio.ActionGroup",
    "Gio.ActionMap",
    "Gio.Icon",
    "Gio.ListModel",
    "Gio.MenuModel",
    "Gtk.Accessible",
    "Gtk.AccessibleRole",
    "Gtk.Actionable",
    "Gtk.Adjustment",
    "Gtk.Align",
    "Gtk.Application",
    "Gtk.ApplicationWindow",
    "Gtk.ArrowType",
    "Gtk.Buildable",
    "Gtk.ConstraintTarget",
    "Gtk.Entry",
    "Gtk.Expression",
    "Gtk.HeaderBar",
    "Gtk.LayoutManager",
    "Gtk.ListBoxRow",
    "Gtk.ListItemFactory",
    "Gtk.ListView",
    "Gtk.Native",
    "Gtk.Orientable",
    "Gtk.Orientation",
    "Gtk.Overflow",
    "Gtk.PackType",
    "Gtk.Popover",
    "Gtk.Root",
    "Gtk.Scrollable",
    "Gtk.ScrollablePolicy",
    "Gtk.ScrolledWindow",
    "Gtk.SelectionModel",
    "Gtk.ShortcutManager",
    "Gtk.Stack",
    "Gtk.Widget",
    "Pango.EllipsizeMode",
]

[[object]]
name = "Gtk.Window"
status = "manual"
trait_name = "GtkWindowExt"
    [[object.property]]
    name = "child"
    # adw use content not child, using it could result in a crash
    ignore = true

[[object]]
name = "Adw.*"
status = "generate"
    [[object.constant]]
    name = "VERSION_S"
    ignore = true
    [[object.function]]
    name = "get_enable_animations"
    rename = "is_animations_enabled"

[[object]]
name = "Adw.AnimationTarget"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.Application"
status = "generate"
builder_postprocess = "Application::register_startup_hook(&ret);"
trait_name = "AdwApplicationExt"
    [[object.function]]
    name = "new"
    manual = true
    # FIXME Remove once
    # https://gitlab.gnome.org/World/Rust/libadwaita-rs/-/merge_requests/8 is in
    [[object.function]]
    name = "get_style_manager"
        [object.function.return]
        nullable = false

[[object]]
name = "Adw.ApplicationWindow"
status = "generate"
trait_name = "AdwApplicationWindowExt"

[[object]]
name = "Adw.CallbackAnimationTarget"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.ComboRow"
status = "generate"
generate_builder = false # manual, to use AsRef<Expression>
manual_traits = ["ComboRowExtManual"]
    [[object.function]]
    name = "set_expression"
    manual = true # use AsRef<Expression> instead of IsA<Expression>
    doc_trait_name = "ComboRowExtManual"

[[object]]
name = "Adw.EnumListModel"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.LeafletPage"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.StyleManager"
status = "generate"
generate_builder = false
    [[object.function]]
    name = "get_system_supports_color_schemes"
    rename = "system_supports_color_schemes"

[[object]]
name = "Adw.SqueezerPage"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.TabBar"
status = "generate"
    [[object.function]]
    name = "setup_extra_drop_target"
    manual = true # somehow gir fails to handle functions that have a array with a specific length
    [[object.signal]]
    name = "extra-drag-drop"
    ignore = true # manual: *mut gobject_ffi::GValue doesn't implement glib::from_glib_borrow

[[object]]
name = "Adw.Toast"
status = "generate"
    [[object.function]]
    name = "set_action_target"
    ignore = true

[[object]]
name = "Adw.ToastOverlay"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.TabPage"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.ViewStackPage"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.Window"
status = "generate"
trait_name = "AdwWindowExt"
