[options]
girs_dir = "../gir-files"
library = "Adw"
version = "1"
min_cfg_version = "1"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
# with this option enabled, versions for gir and gir-files saved only to one file to minimize noise
single_version_file = true
generate_builder = true

external_libraries = [
   "GLib",
   "GObject",
   "Gdk",
   "GdkPixbuf",
   "Gio",
   "Gtk",
   "Pango",
]

generate = [
    "Adw.ActionRow",
    "Adw.ApplicationWindow",
    "Adw.Avatar",
    "Adw.Bin",
    "Adw.Carousel",
    "Adw.CarouselIndicatorDots",
    "Adw.CarouselIndicatorLines",
    "Adw.Clamp",
    "Adw.ClampLayout",
    "Adw.ClampScrollable",
    "Adw.ExpanderRow",
    "Adw.Flap",
    "Adw.HeaderBar",
    "Adw.Leaflet",
    "Adw.LeafletPage",
    "Adw.PreferencesGroup",
    "Adw.PreferencesPage",
    "Adw.PreferencesRow",
    "Adw.PreferencesWindow",
    "Adw.Squeezer",
    "Adw.SqueezerPage",
    "Adw.StatusPage",
    "Adw.SwipeTracker",
    "Adw.ViewSwitcher",
    "Adw.ViewSwitcherBar",
    "Adw.ViewSwitcherTitle",
    "Adw.Window",
    "Adw.WindowTitle",
]

manual = [
    "GLib.Variant",
    "GObject.Object",
    "GObject.Value",
    "Gdk.Cursor",
    "Gdk.Display",
    "Gdk.Rectangle",
    "GdkPixbuf.Pixbuf",
    "Gio.ActionGroup",
    "Gio.ActionMap",
    "Gio.ListModel",
    "Gtk.Accessible",
    "Gtk.AccessibleRole",
    "Gtk.Actionable",
    "Gtk.Adjustment",
    "Gtk.Align",
    "Gtk.Application",
    "Gtk.ApplicationWindow",
    "Gtk.Buildable",
    "Gtk.ConstraintTarget",
    "Gtk.Entry",
    "Gtk.Expression",
    "Gtk.HeaderBar",
    "Gtk.LayoutManager",
    "Gtk.ListBoxRow",
    "Gtk.ListItemFactory",
    "Gtk.Native",
    "Gtk.Orientable",
    "Gtk.Orientation",
    "Gtk.Overflow",
    "Gtk.PackType",
    "Gtk.Root",
    "Gtk.Scrollable",
    "Gtk.ScrollablePolicy",
    "Gtk.SelectionModel",
    "Gtk.ShortcutManager",
    "Gtk.Stack",
    "Gtk.Widget",
    "Gtk.Window",
    "Pango.EllipsizeMode",
]

[[object]]
name = "Adw.*"
status = "generate"

[[object]]
name = "Adw.ComboRow"
status = "generate"
generate_builder = false # manual, to use AsRef<Expression>
manual_traits = ["ComboRowExtManual"]
    [[object.function]]
    name = "set_expression"
    manual = true # use AsRef<Expression> instead of IsA<Expression>
    doc_trait_name = "ComboRowExtManual"

[[object]]
name = "Adw.EnumListModel"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.ValueObject"
status = "generate"
generate_builder = false

# All those are enumerations so it doesn't make sense to generate builders for them
[[object]]
name = "Adw.CenteringPolicy"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.EnumValueObject"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.FlapFoldPolicy"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.FlapTransitionType"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.LeafletTransitionType"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.NavigationDirection"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.SqueezerTransitionType"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.ViewSwitcherPolicy"
status = "generate"
generate_builder = false

# Only buildable in UI files so no need for the builder pattern.
[[object]]
name = "Adw.SwipeGroup"
status = "generate"
generate_builder = false

# For an interface it doesn't make sense either
[[object]]
name = "Adw.Swipeable"
status = "generate"
generate_builder = false

