[options]
girs_directories = ["../gir-files", "../"]
library = "Adw"
version = "1"
min_cfg_version = "1"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
# with this option enabled, versions for gir and gir-files saved only to one file to minimize noise
single_version_file = true
generate_builder = true

external_libraries = [
   "GLib",
   "GObject",
   "Gdk",
   "GdkPixbuf",
   "Gio",
   "Gtk",
   "Pango",
]

generate = [
    "Adw.ActionRow",
    "Adw.ApplicationWindow",
    "Adw.Avatar",
    "Adw.Bin",
    "Adw.Carousel",
    "Adw.CarouselIndicatorDots",
    "Adw.CarouselIndicatorLines",
    "Adw.CenteringPolicy",
    "Adw.Clamp",
    "Adw.ClampLayout",
    "Adw.ClampScrollable",
    "Adw.ExpanderRow",
    "Adw.Flap",
    "Adw.FlapFoldPolicy",
    "Adw.FlapTransitionType",
    "Adw.HeaderBar",
    "Adw.Leaflet",
    "Adw.LeafletTransitionType",
    "Adw.NavigationDirection",
    "Adw.PreferencesGroup",
    "Adw.PreferencesPage",
    "Adw.PreferencesRow",
    "Adw.PreferencesWindow",
    "Adw.Squeezer",
    "Adw.SqueezerTransitionType",
    "Adw.StatusPage",
    "Adw.SwipeTracker",
    "Adw.Swipeable",
    "Adw.TabView",
    "Adw.ViewSwitcher",
    "Adw.ViewSwitcherBar",
    "Adw.ViewSwitcherPolicy",
    "Adw.ViewSwitcherTitle",
    "Adw.Window",
    "Adw.WindowTitle",
]

manual = [
    "GLib.Variant",
    "GObject.Object",
    "GObject.Value",
    "Gdk.Cursor",
    "Gdk.Display",
    "Gdk.DragAction",
    "Gdk.Paintable",
    "Gdk.Rectangle",
    "GdkPixbuf.Pixbuf",
    "Gio.ActionGroup",
    "Gio.ActionMap",
    "Gio.Icon",
    "Gio.ListModel",
    "Gio.MenuModel",
    "Gtk.Accessible",
    "Gtk.AccessibleRole",
    "Gtk.Actionable",
    "Gtk.Adjustment",
    "Gtk.Align",
    "Gtk.Application",
    "Gtk.ApplicationWindow",
    "Gtk.Buildable",
    "Gtk.ConstraintTarget",
    "Gtk.Entry",
    "Gtk.Expression",
    "Gtk.HeaderBar",
    "Gtk.LayoutManager",
    "Gtk.ListBoxRow",
    "Gtk.ListItemFactory",
    "Gtk.ListView",
    "Gtk.Native",
    "Gtk.Orientable",
    "Gtk.Orientation",
    "Gtk.Overflow",
    "Gtk.PackType",
    "Gtk.Root",
    "Gtk.Scrollable",
    "Gtk.ScrollablePolicy",
    "Gtk.ScrolledWindow",
    "Gtk.SelectionModel",
    "Gtk.ShortcutManager",
    "Gtk.Stack",
    "Gtk.Widget",
    "Gtk.Window",
    "Pango.EllipsizeMode",
]

[[object]]
name = "Gtk.Window"
trait_name = "GtkWindowExt"

[[object]]
name = "Adw.*"
status = "generate"
    [[object.function]]
    name = "get_enable_animations"
    rename = "is_animations_enabled"

[[object]]
name = "Adw.ComboRow"
status = "generate"
generate_builder = false # manual, to use AsRef<Expression>
manual_traits = ["ComboRowExtManual"]
    [[object.function]]
    name = "set_expression"
    manual = true # use AsRef<Expression> instead of IsA<Expression>
    doc_trait_name = "ComboRowExtManual"

[[object]]
name = "Adw.EnumListModel"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.EnumValueObject"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.LeafletPage"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.SqueezerPage"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.TabBar"
status = "generate"
    [[object.function]]
    name = "setup_extra_drop_target"
    manual = true # somehow gir fails to handle functions that have a array with a specific length
    [[object.signal]]
    name = "extra-drag-drop"
    ignore = true # manual: *mut gobject_ffi::GValue doesn't implement glib::from_glib_borrow

[[object]]
name = "Adw.TabPage"
status = "generate"
generate_builder = false

[[object]]
name = "Adw.ValueObject"
status = "generate"
generate_builder = false
